# Generated by Django 6.0.3 on 2026-03-31 07:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('sales', '0002_payment'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceExecution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_date', models.DateField()),
                ('next_due_date', models.DateField(blank=True, help_text='Calculée automatiquement depuis execution_date + renewal_delay_days.', null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('reminder_sent', models.BooleanField(default=False)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_executions', to='clients.client')),
                ('sale_item', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='service_execution', to='sales.saleitem')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='executions', to='services.service')),
            ],
            options={
                'verbose_name': 'Exécution de prestation',
                'verbose_name_plural': 'Exécutions de prestations',
                'ordering': ['next_due_date'],
                'indexes': [models.Index(fields=['next_due_date'], name='execution_next_due_idx'), models.Index(fields=['is_completed'], name='execution_completed_idx'), models.Index(fields=['client'], name='execution_client_idx')],
            },
        ),
    ]
