# Generated by Django 6.0.3 on 2026-04-01 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_scheduling_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='tours_per_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 tour / mois — tous les 30 jours'), (2, '2 tours / mois — tous les 15 jours'), (3, '3 tours / mois — tous les 10 jours'), (4, '4 tours / mois — tous les 7 jours')], help_text="Nombre de tours d'entretien par mois. Détermine l'intervalle entre deux passages.", null=True),
        ),
        migrations.AlterField(
            model_name='serviceexecution',
            name='next_due_date',
            field=models.DateField(blank=True, help_text='Calculée automatiquement depuis execution_date + intervalle selon les tours.', null=True),
        ),
    ]
