# Generated by Django 6.0.3 on 2026-04-01 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_add_tours_per_month'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='parent_execution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='services.serviceexecution'),
        ),
    ]
