# Generated by Django 6.0.3 on 2026-05-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_backfill_parent_execution'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='start_tour',
            field=models.PositiveSmallIntegerField(blank=True, help_text='Numéro de ce tour dans le cycle mensuel (1-4). Null = Tour 1.', null=True),
        ),
        migrations.AlterField(
            model_name='serviceexecution',
            name='tours_per_month',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(1, '1 tour / mois — tous les 30 jours'), (2, '2 tours / mois — toutes les 2 semaines'), (3, '3 tours / mois — tous les 10 jours'), (4, '4 tours / mois — toutes les semaines')], help_text="Nombre de tours d'entretien par mois. Détermine l'intervalle entre deux passages.", null=True),
        ),
    ]
