# Generated by Django 6.0.3 on 2026-05-11 13:12

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('products', '0005_add_wholesale_price'),
        ('services', '0007_add_start_tour'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Titre')),
                ('task_date', models.DateField(verbose_name='Date prévue')),
                ('note', models.TextField(blank=True, verbose_name='Notes')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Terminée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='clients.client', verbose_name='Client')),
            ],
            options={
                'verbose_name': 'Tâche',
                'verbose_name_plural': 'Tâches',
                'ordering': ['task_date'],
            },
        ),
        migrations.CreateModel(
            name='TaskProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)], verbose_name='Quantité')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_products', to='products.product')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_products', to='services.task')),
            ],
            options={
                'verbose_name': 'Produit de tâche',
                'verbose_name_plural': 'Produits de tâche',
            },
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['task_date'], name='task_date_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['is_completed'], name='task_completed_idx'),
        ),
        migrations.AddIndex(
            model_name='task',
            index=models.Index(fields=['client'], name='task_client_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='taskproduct',
            unique_together={('task', 'product')},
        ),
    ]
