# Generated by Django 6.0.3 on 2026-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_add_task_taskproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='completed_at',
            field=models.DateField(blank=True, help_text='Date à laquelle la prestation a été marquée comme effectuée.', null=True),
        ),
        migrations.AddField(
            model_name='serviceexecution',
            name='hidden_from_calendar',
            field=models.BooleanField(default=False, help_text='Masquée du calendrier mais toujours dans le système.'),
        ),
    ]
