# Generated by Django 6.0.3 on 2026-06-18 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0009_serviceexecution_completed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceexecution',
            name='original_execution_date',
            field=models.DateField(blank=True, help_text="Date d'origine avant un éventuel report. Utilisée pour calculer le prochain cycle sans décalage.", null=True),
        ),
    ]
