# Generated by Django 6.0.3 on 2026-03-31 07:18

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('phone', models.CharField(blank=True, max_length=25, validators=[django.core.validators.RegexValidator(message='Numéro de téléphone invalide.', regex='^\\+?[\\d\\s\\-]{7,20}$')])),
                ('notes', models.TextField(blank=True, help_text='Informations utiles : préférences, localisation, contexte.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Client',
                'verbose_name_plural': 'Clients',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='client_name_idx'), models.Index(fields=['is_active'], name='client_is_active_idx')],
            },
        ),
    ]
