# Generated by Django 6.0.3 on 2026-05-14 18:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devis', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='quoteitem',
            options={'ordering': ['id'], 'verbose_name': 'Ligne de devis', 'verbose_name_plural': 'Lignes de devis'},
        ),
    ]
