# Generated by Django 6.0.3 on 2026-03-31 07:37

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('stock', 'Achat de stock'), ('transport', 'Transport'), ('equipment', 'Matériel / Équipement'), ('utilities', 'Charges (eau, électricité…)'), ('other', 'Autre')], default='other', max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, help_text='Montant de la dépense en FCFA.', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))])),
                ('expense_date', models.DateField()),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Dépense',
                'verbose_name_plural': 'Dépenses',
                'ordering': ['-expense_date', '-created_at'],
                'indexes': [models.Index(fields=['expense_date'], name='expense_date_idx'), models.Index(fields=['category'], name='expense_category_idx')],
            },
        ),
    ]
