# Generated by Django 6.0.3 on 2026-04-21 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0002_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='saleitem',
            name='label',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
