# Generated by Django 6.0.3 on 2026-05-01 09:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0003_add_label_to_saleitem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='canceled_sales', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='sale',
            name='cancellation_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('canceled', 'Annulée')], db_index=True, default='active', max_length=10),
        ),
        migrations.CreateModel(
            name='SaleModificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField()),
                ('snapshot_before', models.JSONField()),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='sale_modifications', to=settings.AUTH_USER_MODEL)),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='modification_logs', to='sales.sale')),
            ],
            options={
                'verbose_name': 'Historique de modification',
                'verbose_name_plural': 'Historiques de modifications',
                'ordering': ['-modified_at'],
            },
        ),
    ]
