# Generated by Django 6.0.3 on 2026-04-01 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('fish', 'Poisson'), ('accessory', 'Accessoire'), ('aquarium', 'Aquarium')], default='accessory', max_length=20),
        ),
    ]
