# Generated by Django 6.0.3 on 2026-06-08 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_add_wholesale_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='initial_stock',
            field=models.PositiveIntegerField(default=0, help_text='Stock après le dernier réapprovisionnement.'),
        ),
    ]
